### ISSUE TITLE
[generic] labels invalid when using tag with sha

### ISSUE THREAD

**Issue by sebastiangaiser** [community-tooling/charts#246]
Hey, thank you for the generic Helm chart.

since the image tag is [added as value to the default labels](https://github.com/community-tooling/charts/commit/ed28b2cca8e2cb2cc40c91a83b14a68625606ae4) it is not longer possible to use a sha for the image, e.g.

```
    image:
      tag: latest@sha256:6703475278611b5a8871769095cb1b5c624ab4d2d9d3874d81afdbe1cb4b8cce
```

Error message: `[metadata.labels: Invalid value: "latest@sha256:6703475278611b5a8871769095cb1b5c624ab4d2d9d3874d81afdbe1cb4b8cce": must be no more than 63 characters, metadata.labels: Invalid value: "latest@sha256:6703475278611b5a8871769095cb1b5c624ab4d2d9d3874d81afdbe1cb4b8cce": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za │
│ z0-9[][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]`

**Comment by sebastiangaiser** [comment]
@morremeyer can you please have a look

**Comment by morremeyer** [comment]
Oh, that’s unfortunate. Sorry for breaking this, I’ll take a look later!

**Comment by sebastiangaiser** [comment]
The simplest would be undoing your change I linked. Otherwise some replace and trim magic could also work

**Comment by morremeyer** [comment]
I decided to go with some filtering magic, since that allows us to have the label with a meaningful content.

For SHA256 versions, it will now just be the hash, for others it will be filtered to only contain valid characters and truncated to 63 characters. 

Once #262 is merged, you should be good to go again. 
Thanks for the report!
