### ISSUE TITLE
generic: error with app.kubernetes.io/version label when image tag is numeric

### ISSUE THREAD

**Issue by azim273** [community-tooling/charts#279]
**Description:**

I encountered an error while deploying the `generic` Helm chart when using a numeric image tag. The error message is:

    Error: UPGRADE FAILED: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string
        

**Steps to Reproduce:**

1.  Add the community-tooling repo:
    
        helm repo add community-tooling https://community-tooling.github.io/charts/
        helm repo update
                    
    
2.  Attempt to install the chart with a numeric image tag:
    
        helm install my-release community-tooling/generic --set image.tag=1202.3
                    
            

This issue seems to have been introduced in #262

**Comment by morremeyer** [comment]
@azim273 Thanks for the report! Can you try again with 7.5.6 please?

**Comment by azim273** [comment]
> @azim273 Thanks for the report! Can you try again with 7.5.6 please?

Thank you! It's working now.
