### ISSUE TITLE
kube-prometheus-stack-crds not building anymore

### ISSUE THREAD

**Issue by mymasse** [community-tooling/charts#369]
Can somebody look into the kube-prometheus-stack-crds charts, there hasn't been a successful release in 2 weeks. There is an open PR but it's failing pre-commit checks.

We rely on this chart to maintain our kube-prometheus-stack deployment and are now failing behind.

**Comment by morremeyer** [comment]
Thanks for bringing this up so that it is documented!

We already discussed this among maintainers and have planned a solution.
I will implement that tomorrow.

**Comment by morremeyer** [comment]
@mymasse Implemented with https://github.com/community-tooling/charts/pull/370, see in https://github.com/community-tooling/charts/pull/362. 

v65.7.0 is released now.

**Comment by mymasse** [comment]
Already saw the release, thanks for the quick turnaround
